# Generated by Django 5.2 on 2025-04-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='custom_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
